version: '3.9'

services:
  cart_service:
    build:
      context: ./Cart.Service
      dockerfile: Dockerfile
    container_name: cart_service
    ports:
      - '9501:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDb__ConnectionString=mongodb://admin:password@cart_mongo_db:27017/?authSource=admin
      - MessageBus__ConnectionString=Endpoint=sb://servicebus_emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
    networks:
      - service_bus_net
      - cart_net

networks:
  service_bus_net:
    external: true
  cart_net:
    external: true
  catalog_net:
    external: true
