name: CI/CD Prod Catalog.Queries

on:
  push:
    branches:
      - main
    paths:
      - 'src/Catalog.Service/**'
      - '.github/workflows/main_function-app-catalog-query-prod-poland.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Catalog.Service/API.Queries' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EBE104DE43F54B24B33D7E57EA0356DF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D27CE3D147B44C569E608CCC3063991A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_141E590A03014AFD85552B2439C3236A }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'function-app-catalog-query-prod-poland'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
